---
- hosts: ubuntu
  become: yes
  tasks:
  - name: install public keys
    ansible.posix.authorized_key:
      user: admin
      state: present
      key: "{{ lookup('file', '~/.ssh/key.pub') }}"

  - name: change sudoers file
    lineinfile:
      path: /etc/sudoers
      state: present
      regexp: '^%sudo'
      line: '%sudo ALL=(ALL) NOPASSWD: ALL'
      validate: /usr/sbin/visudo -cf %s

- hosts: proxmox
  tasks:
  - name: install-public-keys
    ansible.posix.authorized_key:
      user: root
      state: present
      key: "{{ lookup('file', '~/.ssh/key.pub') }}"
