---
- hosts: ubuntu
  become: yes
  tasks:
    - name: update-nodes
      apt:
        update_cache: yes
        upgrade: 'yes'

- hosts: proxmox
  tasks:
    - name: update-proxmox
      apt:
        update_cache: yes
        upgrade: 'yes'
